apiVersion: v1
kind: Service
metadata:
  name: loanbook-sentinel
  namespace: orbii
  labels:
    app: loanbook-sentinel
spec:
  type: ClusterIP
  selector:
    app: loanbook-sentinel
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
